language: node_js
node_js:
    - "10"
    - "12"
    - "14"

services:
# https://docs.travis-ci.com/user/database-setup/
#  - mongodb
#  - elasticsearch
#  - redis-server

before_script:

script:
    - npm run lint
    - npm test

after_success:

sudo: false
