environment:
  nodejs_version: "8"

install:
  - ps: Install-Product node $env:nodejs_version
  - npm install

before_build:
build: off
after_build:

before_test:
  - node --version
  - npm --version

test_script:
  - C:\projects\haraka-plugin-p0f\node_modules\.bin\mocha

after_test:

